import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className='main-div'>
        <p className='main-h1'>Your Businesses:</p>
        <div className='main-buttons-div'>
        <Link href="crypto">
        <button className='main-buttons'>Crypto</button>
        </Link>
        <Link href="trad">
        <button className='main-buttons'>Traditional</button>
        </Link>
        </div>
        </div>
      </main>
    </>
  )
}
